import { HorizontalBox, VerticalBox, ListView, StandardListView, GroupBox, ComboBox, GridBox } from "std-widgets.slint";
import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";
import { CardData } from "../cards/card_data_struct.slint";
import { Card } from "../cards/card.slint";

export component CardPage inherits Page {
    title: @tr("CardPage");
    show-enable-switch: false;

    in property <CardData> active-card;
    callback trigger_fetch();

    // Fetch once when the tab loads
    init => {
        root.trigger_fetch();
    }

    Card {
        card-data: root.active-card;

        request_new_card => {
            root.trigger_fetch();
        }
    }
}
