// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { CheckBox, StandardListView, ListView } from "std-widgets.slint";
import { AboutPage, DictionaryPage } from "./assets/pages/pages.slint";
import { GallerySettings } from "./assets/gallery_settings.slint";
import { SideBar } from "./assets/side_bar.slint";

export component MotherWindow inherits Window {
    preferred-width: 1600px;
    preferred-height: 800px;
    title: @tr("Slint Widgets Gallery");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Tabs");
            model: [
                @tr("Menu" => "Dictionary"), 
                @tr("Menu" => "About")
            ];
        }

        if(side-bar.current-item == 0) : DictionaryPage {}
        if(side-bar.current-item == 5) : AboutPage {}
    }
}
